config/routes.rb
Rails.application.routes.draw do
  resources :carrinho_vendas
  resources :vendas
  get 'sessions/new'
  get 'users/new'
  resources :clientes
  get "produtos/busca", to: "produtos#busca", as: :busca_produto
  resources :produtos
	root to: "sessions#new"
	resources :users
	get    'sign_in'   => 'sessions#new'
	post   'sign_in'   => 'sessions#create'
	delete 'sign_out'  => 'sessions#destroy'
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  validates :nome, presence: true, length: {maximum: 50}
  validates :cpfOuCnpj, uniqueness: true, on: :validaCPF
  validaCPF = CNPJ.valid?(:cpfOuCnpj) || CPF.valid?(:cpfOuCnpj)
  validates :telefone, presence: true, length: {minimum: 11}
  VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
  before_save do
    self.email = email.downcase
    self.cpfOuCnpj.gsub!(/(\.|\-)/, "")
    self.telefone.gsub!(/(\(|\)|\-)/, "")
  end

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json

  def show
    @cliente = Cliente.find(params[:id])
  end
 

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to clientes_url, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpfOuCnpj, :email, :telefone)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= javascript_include_tag "application" %>
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
    <%= form.label :cpfOuCnpj, "CPF ou CNPJ" %>
    <%= form.text_field :cpfOuCnpj, id: :cpfOuCnpj %>

    <%= form.label :email, "E-mail" %>
    <%= form.text_field :email %>
    <%= form.label :telefone, "Telefone" %>
    <%= form.text_field :telefone, id: :telefone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<% @clientes.each do |cliente| %>
    <tr>
        <td><%= cliente.nome %></td>
        <td><%= link_to 'Ver cliente', cliente, class:"btn btn-default" %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente), class:"btn btn-default" %></td>
        <td><%= link_to 'Deletar', cliente, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' }, class:"btn btn-default" %></td>
    </tr>
<% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar Novo Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>Novo Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

 <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Documento</th>
                    <th>E-mail</th>
					          <th>Telefone</th>
                    <th colspan="2"></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= @cliente.nome %></td>
                    <td><%= @cliente.cpfOuCnpj %></td>
                    <td><%= @cliente.email %></td>
                    <td><%= @cliente.telefone %></td>
                    <td><%= link_to 'Editar', edit_cliente_path(@cliente), class:"btn btn-default" %></td>
                    <td><%= link_to 'Deletar', @cliente, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' }, class:"btn btn-default" %></td>
                </tr>
            </tbody>
 </table>

<%= link_to 'Editar', edit_cliente_path(@cliente), class:"btn btn-default" %> |
<%= link_to 'Voltar', clientes_path, class:"btn btn-default" %>