config/routes.rb
Rails.application.routes.draw do
  resources :carrinho_vendas
  resources :vendas
  get 'sessions/new'
  get 'users/new'
  resources :clientes
  get "produtos/busca", to: "produtos#busca", as: :busca_produto
  resources :produtos
	root to: "sessions#new"
	resources :users
	get    'sign_in'   => 'sessions#new'
	post   'sign_in'   => 'sessions#create'
	delete 'sign_out'  => 'sessions#destroy'
end

app/models/carrinho_venda.rb
class CarrinhoVenda < ApplicationRecord
  belongs_to  :cliente, optional: true
  has_many :venda

  validates :avatar, file_size: { less_than: 1.megabytes }
  mount_uploader :avatar, AvatarUploader

  validates :cliente,  presence: true
end

app/controllers/carrinho_vendas_controller.rb
class CarrinhoVendasController < ApplicationController
  include CarrinhoVendasHelper
  before_action :set_carrinho_venda, only: [:show, :edit, :update, :destroy]

  # GET /carrinho_vendas or /carrinho_vendas.json
  def index
    @carrinho_vendas = CarrinhoVenda.all
  end

  # GET /carrinho_vendas/1 or /carrinho_vendas/1.json
  def show
  end

  # GET /carrinho_vendas/new
  def new
    @vendas = Array.new
    @carrinho_venda = CarrinhoVenda.new
    @produtos = Produto.all
    @clientes = Cliente.all
  end

  # GET /carrinho_vendas/1/edit
  def edit
    renderiza :edit
  end

  # POST /carrinho_vendas or /carrinho_vendas.json
  def create
    @produtos = Produto.all
    @clientes = Cliente.all
    @carrinho_venda = CarrinhoVenda.new
    @vendas = session[:vendas]
    if @vendas == nil
      @vendas = Array.new
    end

    if params[:commit] == 'Adicionar Produto'
      @venda = Venda.new
      produto = params[:carrinho_venda][:venda].values
      @venda.produto_id = produto[0]
      @venda.quantidade = produto[1]
      @vendas << @venda
      session[:vendas] = @vendas
      renderiza :new
    end
    if params[:commit] == 'Salvar'
      respond_to do |format|
        @carrinho_venda = CarrinhoVenda.new(carrinho_venda_params)
        @vendaTotal = Array.new
        retorno = nil
        @vendas.each do |vend|
          if @carrinho_venda.id == nil
            @vendaFeita = retornarVenda(vend)
            @carrinho_venda = @vendaFeita.build_carrinho_venda(:cliente_id => @carrinho_venda.cliente_id, :avatar => @carrinho_venda.avatar )
            retorno = @carrinho_venda.save
            @vendaFeita.carrinho_venda_id = @carrinho_venda.id
            retorno = @vendaFeita.save
          else
            @vendafeita1 = retornarVenda(vend)
            @vendafeita1.carrinho_venda_id = @carrinho_venda.id
            retorno = @vendafeita1.save
          end
        end
        if retorno
          format.html { redirect_to @carrinho_venda, notice: "Carrinho venda was successfully created." }
          format.json { render :show, status: :created, location: @carrinho_venda }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @carrinho_venda.errors, status: :unprocessable_entity }
        end
      end
    end
    if params[:commit] == 'Limpar Vendas'
      session[:vendas] = nil
      renderiza :new
    end
  end

  # PATCH/PUT /carrinho_vendas/1 or /carrinho_vendas/1.json
  def update
    respond_to do |format|
      if @carrinho_venda.update(carrinho_venda_params)
        format.html { redirect_to @carrinho_venda, notice: "Carrinho venda was successfully updated." }
        format.json { render :show, status: :ok, location: @carrinho_venda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carrinho_venda.errors, status: :unprocessable_entity }
      end
    end
  end
  def renderiza(view)
    @clientes = Cliente.all
    @produtos = Produto.all
    render view
  end
  # Only allow a list of trusted parameters through.
  def carrinho_venda_params
    params.require(:carrinho_venda).permit(:cliente_id, :avatar)
  end
  # DELETE /carrinho_vendas/1 or /carrinho_vendas/1.json
  def destroy
    @carrinho_venda.destroy
    respond_to do |format|
      format.html { redirect_to carrinho_vendas_url, notice: "Carrinho venda was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrinho_venda
      @carrinho_venda = CarrinhoVenda.find(params[:id])
    end
end

app/helpers/carrinho_vendas_helper.rb
module CarrinhoVendasHelper

  def nomeProduto(venda)
    ven = retornarVenda(venda)
    produto = Produto.find_by(id: ven.produto_id)
    nome = produto.nome
  end

  def quantidade(venda)
    ven = retornarVenda(venda)
    quantidade = ven.quantidade
  end

  def vendeas
    vendas = session[:vendas]
    if vendas == nil
      vendas = Array.new
    else
      vendas
    end
  end

  def limparVendas
    session[:vendas] = nil
  end

  def retornarVenda(venda)
    if  venda.class.to_s == 'Hash'
      vendeas = Venda.new(venda)
    else
      vendeas = venda
    end
  end
  def formVendas
    session[:vendas]
  end
end

app/views/carrinho_vendas/_form.html.erb
<% @carrinho_venda.errors.full_messages.each do |msg| %>
  <div class="alert alert-danger" role="alert">
    <%= msg %>
  </div>
<% end %>

<%= form_for(@carrinho_venda) do |form| %>


  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :clientes, 'Cliente' %>
        <%=form.collection_select :cliente_id, @clientes, :id, :nome, {}, :prompt => "Selecione", class: "form-control"%>
      </div>
    </div>
  </div>

  <%= form.fields_for :venda do |vendas_f| %>
    <div class="row">
      <div class="col-sm-8">
        <div class="form-group">
          <%= vendas_f.label :produtos, 'Produto' %>
          <%=vendas_f.collection_select :produto_id, @produtos, :id, :nome, {}, :prompt => "Selecione",  class: "form-control"%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-8">
        <div class="form-group">
          <%= vendas_f.label :quantidade, 'Nº de produtos' %>
          <%= vendas_f.text_field :quantidade, class:"form-control" %>
        </div>
      </div>
    </div>
    <div class="actions">
      <tr>
        <td>
           <%= vendas_f.submit "Adicionar Produto"  %>
        </td>
        <td>
          <%= vendas_f.submit 'Limpar Vendas' %>
        </td>
      </tr>
    </div>

    <table class="table table-bordered table-hover">
        <thead>
        <% if formVendas %>
          <tr>
            <th>Produto</th>
            <th>quantidade</th>
          </tr>
        <% end %>
       </thead>
       <tbody>
        <% vendeas.each do |venda| %>
       <tr>
         <td><%= nomeProduto(venda) %></td>
         <td><%= quantidade(venda) %></td>
       </tr>
       <% end %>
      </tbody>
    </table>
    </br>
  <% end %>
  <div class="row">
    <div class="col-sm-8">
      <div class="form-group">
        <%= form.label :avatar, 'Comprovante da venda' %>
        <%= form.file_field :avatar, class:"form-control"%>
      </div>
    </div>
  </div>
  <%= form.submit texto_da_acao %>

<% end %>

app/views/carrinho_vendas/edit.html.erb
<h1>Editar Venda</h1>

<%= render partial: "form", locals: {texto_da_acao: "Atualizar"} %>

<%= link_to 'Show', @carrinho_venda %> |
<%= link_to 'Back', carrinho_vendas_path %>

app/views/carrinho_vendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carrinho Vendas</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th></th>
      <th>Avatar</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carrinho_vendas.each do |carrinho_venda| %>
      <tr>
        <td><%= carrinho_venda.cliente.nome %></td>
        <td><%= carrinho_venda.avatar %></td>
        <td><%= link_to 'Show', carrinho_venda %></td>
        <td><%= link_to 'Edit', edit_carrinho_venda_path(carrinho_venda) %></td>
        <td><%= link_to 'Destroy', carrinho_venda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrinho Venda', new_carrinho_venda_path %>

app/views/carrinho_vendas/new.html.erb
<h1>Nova Venda</h1>

<%= render partial: "form", locals: {texto_da_acao: "Salvar"} %>

<%= link_to 'Back', carrinho_vendas_path %>

app/views/carrinho_vendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @carrinho_venda.cliente.nome %>
</p>

<table class="table table-bordered table-hover">
  <thead>
  <% if @carrinho_venda.venda %>
    <tr>
      <th>Produto</th>
      <th>quantidade</th>
    </tr>
  <% end %>
  </thead>
  <tbody>
  <% @carrinho_venda.venda.each do |venda| %>
    <tr>
      <td><%= venda.produto.nome %></td>
      <td><%= venda.quantidade %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<p>
  <strong>Comprovante da venda: </strong>
  <%= image_tag @carrinho_venda.avatar_url.to_s %>
</p>

<%= link_to 'Edit', edit_carrinho_venda_path(@carrinho_venda) %> |
<%= link_to 'Deletar', @carrinho_venda, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' }, class:"btn btn-default" %> |
<%= link_to 'Back', carrinho_vendas_path %>