config/routes.rb
Rails.application.routes.draw do
  resources :carrinho_vendas
  resources :vendas
  get 'sessions/new'
  get 'users/new'
  resources :clientes
  get "produtos/busca", to: "produtos#busca", as: :busca_produto
  resources :produtos
	root to: "sessions#new"
	resources :users
	get    'sign_in'   => 'sessions#new'
	post   'sign_in'   => 'sessions#create'
	delete 'sign_out'  => 'sessions#destroy'
end

app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to  :produto, optional: true
  belongs_to  :carrinho_venda, optional: true

  validates :quantidade, :produto, :carrinho_venda,  presence: true
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :set_venda, only: [:show, :edit, :update, :destroy]
  def new
    @venda = Venda.new
    @produtos = Produto.all
    @clientes = Cliente.all
  end
  def edit
    renderiza :edit
  end

  def update
    if @venda.update venda_params
      flash[:notice] = "Produto atualizado com sucesso!"
      redirect_to vendas_path
    else
      renderiza :edit
    end
  end

  def destroy
    @venda.destroy
    redirect_to vendas_path
  end

  def show
    @venda = Venda.find(params[:id])
  end

  def index
    @vendas = Venda.all
  end

  def create
    @venda = Venda.new venda_params
    @produtos = Produto.all
    @clientes = Cliente.all
    respond_to do |format|
      if @venda.save
        format.html { redirect_to vendas_url, notice: 'Venda foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @venda }
      else
        format.html { render :new }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end
  def renderiza(view)
    @clientes = Cliente.all
    @produtos = Produto.all
    render view
  end
  # Only allow a list of trusted parameters through.
  def venda_params
    params.require(:venda).permit(:quantidade, :produto_id, :carrinho_venda_id)
  end

  def set_venda
    @venda = Venda.find(params[:id])
  end

end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/vendas/_form.html.erb
  <% if @venda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venda.errors.count, "error") %> prohibited this venda from being saved:</h2>

      <ul>
        <% @venda.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @venda do |form| %>
    <div class="row">
      <div class="col-sm-8">
        <div class="form-group">
          <%= form.label :quantidade, 'Nº de produtos' %>
          <%= form.text_field :quantidade, class:"form-control" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-8">
        <div class="form-group">
          <%= form.label :produtos, 'Produto' %>
          <%=form.collection_select :produto_id, @produtos, :id, :nome, {}, class: "form-control"%>
        </div>
      </div>
    </div>
    <%= form.submit texto_da_acao,class:"btn btn-primary" %>
  <% end %>

app/views/vendas/edit.html.erb
<h1>Editar Venda</h1>

<%= render partial: "form", locals: {texto_da_acao: "Atualizar"} %>

<%= link_to 'Show', @venda %> |
<%= link_to 'Back', vendas_path %>

app/views/vendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendas</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Produto</th>
      <th>Quantidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendas.each do |venda| %>
      <tr>
        <td><%= venda.produto.nome %></td>
        <td><%= venda.quantidade %></td>
        <td><%= link_to 'Visualizar', venda %></td>
        <td><%= link_to 'Alterar', edit_venda_path(venda) %></td>
        <td><%= link_to 'Deletar', venda, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venda', new_venda_path %>

app/views/vendas/new.html.erb
<h1>Nova Venda</h1>

<%= render partial: "form", locals: {texto_da_acao: "Salvar"} %>

<%= link_to 'Back', vendas_path %>

app/views/vendas/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Produto</th>
      <th>Quantidade</th>
      <th colspan="2"></th>
    </tr>
  </thead>
    <tbody>
    <tr>
      <td><%= @venda.produto.nome %></td>
      <td><%= @venda.quantidade %></td>
      <td><%= link_to 'Alterar', edit_venda_path(@venda) %></td>
      <td><%= link_to 'Deletar', @venda, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' } %></td>
    </tr>
    </tbody>
</table>


<%= link_to 'Edit', edit_venda_path(@venda) %> |
<%= link_to 'Back', vendas_path %>