config/routes.rb
Rails.application.routes.draw do
  resources :carrinho_vendas
  resources :vendas
  get 'sessions/new'
  get 'users/new'
  resources :clientes
  get "produtos/busca", to: "produtos#busca", as: :busca_produto
  resources :produtos
	root to: "sessions#new"
	resources :users
	get    'sign_in'   => 'sessions#new'
	post   'sign_in'   => 'sessions#create'
	delete 'sign_out'  => 'sessions#destroy'
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul>
        <% if logged_in? %>
          <li>
			<ul>
				<%= link_to "Users", users_path %>
			</ul>
		  </li>
          <li>
            <ul>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings",edit_user_path(current_user) %></li>
              <li>
                <%= link_to "Log out", sign_out_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
			<ul>
				<%= link_to "Log in", root_path %>
			</ul>
			<ul>
				<%= image_tag "farda.jpg" %>
			</ul>
		  </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render "layouts/header" %>
	<%= nav_bar brand: "Loja", brand_link: produtos_path do %>
	  <%= menu_group do %>
		<%= menu_item "Criar novo produto", new_produto_path %>
		<%= menu_item "Clientes", clientes_path %>
      <%= menu_item "Vendas", carrinho_vendas_path %>
	  <% end %>
	  <%= form_tag busca_produto_path, method: :get, class:"navbar-form navbar-right" do %>
	  <div class="form-group">
		<%= text_field_tag :nome, @nome, class:"form-control" %>
		<%= button_to "Buscar", nil, class:"btn btn-default" %>
	  </div>
	<% end %>
	<% end %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>